# Generated by Django 4.0.5 on 2022-06-26 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
