# Generated by Django 3.2.13 on 2022-06-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_alter_car_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('parentId', models.CharField(max_length=64, verbose_name='ParentID')),
                ('price', models.CharField(max_length=64, verbose_name='Price')),
                ('date', models.CharField(max_length=64, verbose_name='Date')),
                ('children', models.CharField(max_length=64, verbose_name='Children')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
