# Generated by Django 3.2.13 on 2022-06-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220623_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='children',
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParentID', to='cars.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
    ]
