# Generated by Django 3.2.13 on 2022-06-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20220624_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parentId',
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='cars.item'),
        ),
    ]
