# Generated by Django 3.2.13 on 2022-06-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_item_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='parent',
            new_name='parentId',
        ),
    ]
