# Generated by Django 3.2.13 on 2022-06-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_parent_item_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='parentId',
            new_name='parent',
        ),
    ]
